# Deployment settings
name: eqcms-notification-service
componentsLabel: notification-service
replicaCount: 1
namespace: cms

# App settings
secretName: eqsitecms-notification-service-secret
containerPort: 8000
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

# Image settings
image: ghcr.io/igor-526/eqsitecms-notification-service
imagePullSecertName: ghcr-secret
imageTag: latest

migration:
  command: ["uv", "run", "alembic", "-c", "alembic.ini", "upgrade", "head"]
  workingDir: /app/src